language: node_js
node_js:
  - "v8.10.0"
cache:
  directories:
  - node_modules
script:
  - npm run test
notifications:
  email:
    - ethdud1@gmail.com
    - esung1129@gmail.com
    - zx6658@naver.com
